#!/bin/bash -
#===============================================================================
#
#          FILE: _xdo.sh #
#         USAGE: ./_xdo.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: Tuesday 17 July 2012 07:55:19  IST IST
#      REVISION:  ---
#===============================================================================

#set -o nounset                              # Treat unset variables as an error
waittime=3
sleep $waittime

count=$1
cmd=$2
cmd1=$3

num=${#count}
if test $num -eq 0
then
    echo usage : $0 count controchar char
    echo count not given.
    exit -1
fi

num=${#cmd}
if test $num -ne 1
then
    echo usage : $0 count controchar char
    echo single control char expected.
    exit -1
fi

num=${#cmd1}
if test $num -ne 1
then
    echo usage : $0 count controchar char
    echo single additional char expected
    exit -1
fi

while test $count -gt 0
do
    count=$((count-1))
    xdotool key ctrl+$cmd $cmd1 ctrl+b o
done
#      #upperChar=${origChar^^}
