#!/bin/bash -
#===============================================================================
#
#          FILE: test.sh
#
#         USAGE: ./test.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: Sunday 19 August 2012 01:56:45  IST IST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error
if [[ $# == 0 || $1 == --help ]]
then
    echo cmd file not given
    exit -1
fi
cmdFile=$1

tmux new-session -d -s bulkcmds
sleep 1
cat $* | while read cmd ;
do
    tmux select-layout -t bulkcmds:0 tiled > /dev/null 2> /dev/null
    tmux  split-window -h -t bulkcmds:0  "$cmd ; echo $? ; bash ; sleep 100" #"echo $i; sleep 100" #\; split-window -d \; attach
done

tmux send-keys -t bulkcmds:0.0  "exit" Enter
tmux select-pane -t bulkcmds:0.0
tmux select-layout -t bulkcmds:0 tiled      > /dev/null 2> /dev/null
#tmux set-option -t bulkcmds:0  synchronize-panes on
tmux -2 attach-session -t bulkcmds
