#!/bin/bash -
#===============================================================================
#
#          FILE: gterm.sh
#
#         USAGE: ./gterm.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: Monday 20 August 2012 12:21:06  IST IST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error
gnome-terminal
