#!/bin/bash -
#===============================================================================
#
#          FILE: Open with Vim.sh
#
#         USAGE: ./Open with Vim.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (),
#  ORGANIZATION:
#       CREATED: Wednesday 23 May 2012 03:44:17  IST IST
#      REVISION:  ---
#===============================================================================
# script location : /home/sandeep/.gnome2/nautilus-scripts

#set -o nounset                              # Treat unset variables as an error

dir=`pwd`

base="`echo $NAUTILUS_SCRIPT_CURRENT_URI | cut -d'/' -f3- | sed 's/%20/ /g'`"
if [ -z "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ]; then
    dir="$base"
else
    while [ ! -z "$1" -a ! -d "$base/$1" ]; do shift; done
    dir="$base/$1"
fi
#gnome-terminal --working-directory="$dir"
gvim -c "VE $dir" -c tabonly -c "colorscheme darkZ"
